

export const metadata = {
    title: 'Not found',
    description: 'Generated by Next.js',
  }
  

export default function NotFound(){
    return (
        <div>
            <h1>Not found</h1>
        </div>
    );
}