export const metadata = {
    title: "Main",
    description: 'Generated by Next.js',
  }

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
        {children}
        {/* &copy; Next JS is great! */}
    </div>
  );
}
